### ISSUE TITLE
File name does not exist when we open the share link after uploading （文件能够成功上传，但是点开分享链接后显示文件无文件名）

### ISSUE THREAD

**Issue by wuyujack** [Mikubill/cowtransfer-uploader#12]
Hi, 

I use the ` -cookie` to upload the large file to my account since I registered as a pro account. Although the uploading is successful and also return the share link, I find that in my account History, the uploaded file has no description and **_no file name_** :

![Screenshot-1](https://user-images.githubusercontent.com/10961996/82730095-b3104d80-9cc2-11ea-979f-20da2aa58aa7.png)

And when I redownload the file with the link, the error appears:

![Screenshot-2](https://user-images.githubusercontent.com/10961996/82730121-fe2a6080-9cc2-11ea-9847-e53348eef483.png)

I also test the uploading without using the cookie, the uploading is successful but the file also do not have a name when I open the share link:

![no_name](https://user-images.githubusercontent.com/10961996/82731253-130af200-9ccb-11ea-8490-17dd3fc8d518.png)

As the file does not have a name, it can not be transferred to the cloud and when you want to download the file, you must use the `-o` to specify the file name, otherwise, it may return an error.

I noticed that the cow-transfer has updated its product recently, will it relate to this bug?

中文：

楼主你好，今天使用的时候我通过 `-cookie` 来上传大型文件到我的账户中，上传是成功的并且返回了分享链接，然而点开分享链接以后点击转存到我的网盘的时候，一直没有反应，于是我就去“历史” 处查看，发现我是有上传记录的，然而上传记录里面文件根本没有文件名，在”历史“里点 转存 网盘也没有反应。

我就尝试下载看看能不能行，然后发现在不使用 `-o` 去声明下载文件的文件名的话，会报错。

为了排除是因为使用了cookie导致的bug，我去掉cookie直接进行上传，然后得到的结果是一样，即上传成功但是点开分享链接以后文件是没有文件名的。

我看到最近奶牛更新了他们产品，这个bug会不会和他们最近的更新有关？

**Comment by Mikubill** [comment]
先暂时使用`-o`指定下载文件名。问题正在排查，可能与API的提交信息有关

**Comment by Mikubill** [comment]
已更新。使用最近版本重试https://github.com/Mikubill/cowtransfer-uploader/releases/tag/v0.4.9

**Comment by wuyujack** [comment]
> 已更新。使用最新版本重试https://github.com/Mikubill/cowtransfer-uploader/releases/tag/v0.4.9

测试成功，感谢！
