### ISSUE TITLE
[Error]文件大于10G 生成链接不能下载

### ISSUE THREAD

**Issue by erichhhhho** [Mikubill/cowtransfer-uploader#13]
![image](https://user-images.githubusercontent.com/17566212/83191696-03762800-a167-11ea-982e-f9f36a8b9576.png)

failed DownloadConfig with error: link unavailable, 404 Not Found, onfile: xxx.zip
version: cowtransfer-uploader_0.4.9_linux_amd64.tar.gz

**Comment by erichhhhho** [comment]
@Mikubill 网页端上传是没有问题的

**Comment by Mikubill** [comment]
链接可以通过网页下载吗？

**Comment by erichhhhho** [comment]
网页端上传后 获得的链接在terminal和网页都能下载

**Comment by Mikubill** [comment]
应该是https://github.com/Mikubill/transfer/issues/9 类似的问题，那边解决以后把代码同步过来
