### ISSUE TITLE
使用命令行下载报错:failed DownloadConfig with error: link unavailable, 403 Forbidden, onfile: 

### ISSUE THREAD

**Issue by dahvlh** [Mikubill/cowtransfer-uploader#14]
使用命令行下载报错:failed DownloadConfig with error: link unavailable, 403 Forbidden, onfile: 
详细log已经上传:  https://c-t.work/s/615c17282b5e4b

版本信息:
cowTransfer-uploader
Source: https://github.com/Mikubill/cowtransfer-uploader
Build: f6bf962e57d326afdf8f7ce3715135498616d703

**Comment by Mikubill** [comment]
已复现。可能是编码转换的问题，稍后我试着修复一下

**Comment by culeao** [comment]
下载时同样遇到 403 错误

**Comment by pongfcnkl** [comment]
同

**Comment by Mikubill** [comment]
已在4.10中修复了这个问题。使用最新版本重试
