### ISSUE TITLE
curl -sL https://git.io/cowtransfer | sh 失败

### ISSUE THREAD

**Issue by lingr7** [Mikubill/cowtransfer-uploader#15]
测试发现，https://git.io/cowtransfer会转移到
https://raw.githubusercontent.com/Mikubill/cowtransfer-uploader/master/install.sh?
但是curl这个文件再导入sh失败了。
【已解决】解决方案，采用其他工具，pasteme.cn工具解决
![image](https://user-images.githubusercontent.com/37898999/87666484-4766d000-c79b-11ea-860c-65ffdd712edd.png)

有无其他好办法。

**Comment by Mikubill** [comment]
我这里测试没问题来着……可以把报错信息发出来吗

**Comment by lingr7** [comment]
运行curl -sL https://git.io/cowtransfer | sh 报错
```
 0curl: (7) Failed to connect to github.com port 443: Connection refused

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by Mikubill** [comment]
安装脚本在执行过程中需要访问 api.github.com 获取最新release，看起来这个域名在部分地区不太可用

可以直接在release页面下载使用。

**Comment by lingr7** [comment]
套娃操作写了篇博客[下载github上文件与release的安装包 - lingr7 - 博客园](  https://www.cnblogs.com/lingr7/p/12697280.html)
