### ISSUE TITLE
Https proxy

### ISSUE THREAD

**Issue by stevewongv** [Mikubill/cowtransfer-uploader#21]
服务器上需要通过https proxy 访问外网，直接下载会报如下错误：
Error: getDownloadDetails returns error: Get "https://cowtransfer.com/transfer/transferdetail?url=xxxxxxxxxxx&treceive=undefined&passcode=": proxyconnect tcp: tls: first record does not look like a TLS handshake%

**Comment by Mikubill** [comment]
可以试试使用HTTP_PROXY（不是HTTPS_PROXY）变量指定https proxy（via https://golang.org/doc/go1.10#net/http

**Comment by stevewongv** [comment]
Ok，解决，感谢🙏
