### ISSUE TITLE
Returned error while uploading file, no progress has been made.

### ISSUE THREAD

**Issue by subsys-R9boq8** [Mikubill/cowtransfer-uploader#22]
Running in verbose mode returned these messages to stdout:
https://pb.envs.net/?b3273873efcea7a8#DYvw54wzkTvRLePgWfitgwq6Qv2dNvfnEnCjFzRNfkZp

Raspberry Pi 3, Debian 10.4 stable, Linux kernel 4.1.19

**Comment by Mikubill** [comment]
问题无法复现（请提供相关环境信息），从日志上看可能是网络不佳
