### ISSUE TITLE
上传成功后，下载提示文件不存在

### ISSUE THREAD

**Issue by majq1990** [Mikubill/cowtransfer-uploader#25]
Destination: https://cowtransfer.com/s/783f22358cd24d
Local: ../elasticsearch:7.6.1-arm64.tar
973.92 MiB / 973.92 MiB [----------------------------------------------------------] 100.00% 245.34 KiB p/s 1h7m45s
Short Download Code: 190991

在其他机器下载：
[root@host-192-168-105-165 soft]# ./cowtransfer-uploader -p 16 https://cowtransfer.com/s/783f22358cd24d
Remote: https://cowtransfer.com/s/783f22358cd24d
File save to: elasticsearch:7.6.1-arm64.tar
0 B / 973.92 MiB [________________________________________________________________________________] 0.00% ? p/s 11s
failed DownloadConfig with error: link unavailable, 404 Not Found, onfile: elasticsearch:7.6.1-arm64.tar
[root@host-192-168-105-165 soft]# 

求指导？

**Comment by Mikubill** [comment]
新版本应该已经修复了这个问题，可以用新版本重新试试。
