### ISSUE TITLE
无法使用这个方法下载数据，

### ISSUE THREAD

**Issue by TrumanZYX** [Mikubill/cowtransfer-uploader#26]
cowtransfer-uploader https://zhuyuexin96.cowtransfer.com/s/2b08e3722ecf4f
Remote: https://zhuyuexin96.cowtransfer.com/s/2b08e3722ecf4f

之后就失败了，请问出现什么错误

**Comment by Mikubill** [comment]
问题确认，请等待修复。

**Comment by Mikubill** [comment]
已修复，使用最新版本下载即可。

**Comment by JinhuaLiang** [comment]
您好，发现这个问题已经关了。但2021.02我又遇到了这个问题
Remote: https://lsy.cowtransfer.com/s/325e5475edb34b
Error: unmatshal DownloadDetails returns error: unexpected end of JSON input

**Comment by Mikubill** [comment]
我这边测试好像没有问题。可以试试用最新发布的版本来下载
