### ISSUE TITLE
下载文件的时候会出现问题，比如我上传了140个文件，使用-s,但是下载不能下载完全，只能下载里面的25个

### ISSUE THREAD

**Issue by TrumanZYX** [Mikubill/cowtransfer-uploader#27]
代码：cowtransfer-uploader -p 128 --hash  https://zhuyuexin96.cowtransfer.com/s/a7abb2aa5fce4e
不知道能否修改，同时希望有功能能出现MD5计算的方法，因为有时候下载的文件虽然下载成功了，但是md5有问题。

**Comment by Mikubill** [comment]
已加入分页支持，下载hash可能要晚些才能加入。
另下载一般不容易出错，出错也有可能是上传的问题（建议在上传时使用`--hash`选项以保证文件正确上传）

**Comment by TrumanZYX** [comment]
> 已加入分页支持，下载hash可能要晚些才能加入。
> 另下载一般不容易出错，出错也有可能是上传的问题（建议在上传时使用`--hash`选项以保证文件正确上传）

感谢回复，这个我使用了上传--hsah，我目前主要使用是为了下载国外的数据，使用国外服务器上传，国内服务器下载，所以不知道除了上传的时候使用--hash，还有什么办法？（注：我一直使用--hash）

**Comment by TrumanZYX** [comment]
分页支持依旧失败，下载数量依旧被限制

**Comment by Mikubill** [comment]
使用新版本(v0.4.15)即可
