### ISSUE TITLE
使用奶牛快传下载软件包，点击下载后，每次都是这个提示：{"error":"Document not found"}

### ISSUE THREAD

**Issue by ywgf88** [Mikubill/cowtransfer-uploader#28]
{"error":"Document not found"}

我注册了账号也是这个提示，不知道怎么解决？

**Comment by Mikubill** [comment]
有可能是上传人未成功上传文件。

**Comment by ywgf88** [comment]
> 有可能是上传人未成功上传文件。

但是我这边显示都是正常的，点进去看也正常，就是不能下载。同样的用wetransfer就可以下载，无需登录。

**Comment by Mikubill** [comment]
之前已经有人反馈过这个问题 https://github.com/Mikubill/transfer/issues/9

具体表现就是正常上传，页面也可以打开就是不能下载。查看日志以后确定是文件未成功上传（一般是网络问题造成的），所以如果是你自己在用的话可以试试重新传一遍

**Comment by hellodword** [comment]
同样的问题

**Comment by Mikubill** [comment]
目前cowtransfer使用应该是正常的。如仍出现这个错误请重新开issue并把日志附上
