### ISSUE TITLE
上传的文件无法下载

### ISSUE THREAD

**Issue by njzjz** [Mikubill/cowtransfer-uploader#3]
https://cowtransfer.com/s/0ed3eeae6d3145

用网页下载也不行，提示{"error":"Document not found"}
![image](https://user-images.githubusercontent.com/9496702/78626131-d63e8500-785b-11ea-851c-42d79ac43418.png)

客服说是“这种情况一般是上传文件不完整”，但是我试了几次都是这种情况，或许是cowtransfer-uploader的问题？

**Comment by Mikubill** [comment]
可以用`-verbose`把上传时的日志输出一下，然后贴上来.
Exp: 怀疑可能是上传token过期导致的问题
```
./cowtransfer-uploader --verbose <your-file>
```

**Comment by Mikubill** [comment]
刚刚试着修复了登陆后上传的prefix问题，可以用新版程序测试一下

https://github.com/Mikubill/cowtransfer-uploader/releases/tag/v0.4.2-beta

**Comment by njzjz** [comment]
> 刚刚试着修复了登陆后上传的prefix问题，可以用新版程序测试一下
> 
> https://github.com/Mikubill/cowtransfer-uploader/releases/tag/v0.4.2-beta

这个版本没有问题了

**Comment by njzjz** [comment]
另外谢谢你开发了这个工具！对我的帮助极大。
