### ISSUE TITLE
今天早上之后所有上传的文件点击下载都是提示{"error":"Document not found"} 

### ISSUE THREAD

**Issue by Aixzk** [Mikubill/cowtransfer-uploader#30]
今天凌晨还用着程序调用 cowtransfer-uploader 上传文件，上传后的文件也是能正常下载的。
但到了早上之后，上传显示是成功，点开页面也能显示文件和大小，但是一点下载就跳新页面显示{"error":"Document not found"}。
同一个文件在网页手动上传并没有这个问题，目前用 cowtransfer-uploader 上传的所有文件都是这样。
在调用时附加 -v 参数后能看到有一条错误的返回信息：
`returns:` {"error":"incorrect region, please use up-fog-cn-east-1.qiniup.com"}`
希望能修复一下，感谢！

**Comment by Mikubill** [comment]
Fix at https://github.com/Mikubill/cowtransfer-uploader/commit/3b86f87f6d4a6f201d8fb79a19955061225d7bcf
已发布新版本

**Comment by Aixzk** [comment]
> Fix at [3b86f87](https://github.com/Mikubill/cowtransfer-uploader/commit/3b86f87f6d4a6f201d8fb79a19955061225d7bcf)
> 已发布新版本

十分感谢！

**Comment by hellodword** [comment]
[3b86f87](https://github.com/Mikubill/cowtransfer-uploader/commit/3b86f87f6d4a6f201d8fb79a19955061225d7bcf) 依然会出现

**Comment by Mikubill** [comment]
@hellodword 测试正常通过（参考 https://github.com/Mikubill/cowtransfer-uploader/runs/2088440054 ），建议另外开一个issue并把日志附上（使用`-v`显示详细日志）
