### ISSUE TITLE
上传好像失效了

### ISSUE THREAD

**Issue by a83376114** [Mikubill/cowtransfer-uploader#31]
上传以后，可以在官网上查看对应的下载页面，但是一点下载就报错 {"error":"Document not found"}。

手动在官网上传以后，可以在终端里使用此脚本下载。

**Comment by Mikubill** [comment]
测试上传没好像问题，可以提供一下使用的版本和上传命令吗（或者用最新版本重新试试

**Comment by Janhen** [comment]
我也遇到过，使用最新的版本正常上传和下载了

相关版本信息： 
之前的版本 0.4.11
cowTransfer-uploader --version
cowTransfer-uploader
Source: https://github.com/Mikubill/cowtransfer-uploader
Build: d10f032d0382d2a889a751eac6bc0a99bd457e35

更新后的版本 0.4.17
cowTransfer-uploader --version
cowTransfer-uploader
Source: https://github.com/Mikubill/cowtransfer-uploader
Build: 3b86f87f6d4a6f201d8fb79a19955061225d7bcf
