### ISSUE TITLE
Error: link invalid & link unavailable, 404 Not Found

### ISSUE THREAD

**Issue by hiiiyilingzhang** [Mikubill/cowtransfer-uploader#32]
Hello！
我成功上传文件后（remember-me登陆自己的账号传的），出现了无法下载的情况：
链接和密码均输入正确，但显示报错：**Error: link invalid**，版本0.4.17
麻烦开发者解答，谢谢啦~

**Comment by Mikubill** [comment]
测试了一下应该是没问题的，能否提供出错时的日志信息（使用 --verbose 选项输出即可

**Comment by hiiiyilingzhang** [comment]
抱歉！终端已关闭尚未截图。检查命令时发现，是由于加了`--password`参数后，下载是未写自己设的密码，而是用了输出的Short Download Code。但是这两天文件下载时均报如下错：
```bash
failed DownloadConfig with error: link unavailable, 404 Not Found, onfile: test.txt
```
日志信息：
![image](https://user-images.githubusercontent.com/81615397/113501529-663f0980-9558-11eb-8fdd-abe8613d7596.png)

![image](https://user-images.githubusercontent.com/81615397/113501541-7f47ba80-9558-11eb-9898-a754d7198efb.png)

**Comment by Mikubill** [comment]
从日志看有可能是上传错误导致的。能否提供上传时的日志信息

**Comment by hiiiyilingzhang** [comment]
命令：
```bash
./cowtransfer-uploader -v -cookie='remember-me=test;' \
/public/workspace/data/Homo_sapiens_assembly38.dict
```
![image](https://user-images.githubusercontent.com/81615397/113501681-b5396e80-9559-11eb-863d-d1193b057bbd.png)
![image](https://user-images.githubusercontent.com/81615397/113501722-f598ec80-9559-11eb-97ee-34bb2ee6a409.png)

**Comment by Mikubill** [comment]
程序版本过旧，更新到新版程序即可。
直接通过命令更新或者在 https://github.com/Mikubill/cowtransfer-uploader/releases 下载

注意检查版本号是否为如下内容
```
 ./cowtransfer-uploader --version

cowTransfer-uploader
Source: https://github.com/Mikubill/cowtransfer-uploader
Build: 3b86f87f6d4a6f201d8fb79a19955061225d7bcf
```

**Comment by hiiiyilingzhang** [comment]
好的，谢谢噢~
