### ISSUE TITLE
大佬有考虑支持MacOS吗

### ISSUE THREAD

**Issue by yinming520108** [Mikubill/cowtransfer-uploader#33]
😀

**Comment by Mikubill** [comment]
支持MacOS，发布页面里的Darwin就是了
https://github.com/Mikubill/cowtransfer-uploader/releases/download/v0.4.17/cowtransfer-uploader_0.4.17_darwin_amd64.tar.gz

2021年4月7日(水) 21:38 yinming520108 ***@***.***>:
