### ISSUE TITLE
Error: unmatshal DownloadDetails returns error: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by taofei-zeng** [Mikubill/cowtransfer-uploader#36]
您好，请问我在用这个命令在服务器上下载数据的时候报错，请问这是什么原因？谢谢！

cowtransfer-uploader --password=112233 https://cowtransfer.com/fafawerawfafg
Error: unmatshal DownloadDetails returns error: invalid character '<' looking for beginning of value

**Comment by master-XS** [comment]
楼主解决了吗

**Comment by Mikubill** [comment]
用最新版本程序重试。如果还有错误把日志贴一下（加上`-v`参数即可输出日志

**Comment by Cc-a23187** [comment]
add -v

**Comment by Cc-a23187** [comment]
加上-v后

`</body><script>if (document.documentMode || +(navigator.userAgent.match(/MSIE (\d+)/) && RegExp.$1)) {
    let frame = document.createElement('iframe');
    frame.setAttribute("border", "0");
    frame.setAttribute("frameborder", "0");
    frame.setAttribute("style", "width: 100%; height: 100%; margin: 0; padding: 0; position: absolute; top: 0; left: 0;");
    frame.src = "https://background.c-t.work/assets/error/Ieerror.html";
    document.body.appendChild(frame);
  }</script></html>
Error: unmatshal DownloadDetails returns error: invalid character '<' looking for beginning of value`
