### ISSUE TITLE
File size exceed, no payment found

### ISSUE THREAD

**Issue by Esther0107** [Mikubill/cowtransfer-uploader#38]
设置了cookie，文件大小10G左右
上传的时候提示 File size exceed, no payment found

Ubuntu 18.04.5 LTS (GNU/Linux 5.11.22-2-pve x86_64)
version=v0.4.18

**Comment by Aixzk** [comment]
奶牛快传前段时间有改动，原 cookie remember-me 要换成新的 remember-mev2 才行，具体可参考 #37

**Comment by Aixzk** [comment]
@Mikubill 文档也该更新一下啦

**Comment by Esther0107** [comment]
哇！感恩~的心~

**Comment by Aixzk** [comment]
新cookie也不行了好像
