### ISSUE TITLE
建议: 添加静默上传功能 (无进度条)

### ISSUE THREAD

**Issue by SuLingGG** [Mikubill/cowtransfer-uploader#4]
Dalao 的 cowtransfer-uploader 项目现在已经在 Github Action 上得到了广泛应用~ (用来上传编译生成的 Artifacts)

但是在 Github Action 的日志中会记录进度条的每一次更新，所以可能会在 Github Action 的日志中打印出几百条进度信息，造成可读性下降。

比如: <https://github.com/SuLingGG/Test-Action/runs/562161933>

( Github Action 核心代码来自: <https://github.com/P3TERX/Actions-OpenWrt>)

所以冒昧地请求 Dalao 加入静默上传功能，也就是在上传过程中不显示进度条，这样对于 Github Action 的日志记录方式来说可读性将大大加强~

**Comment by Mikubill** [comment]
功能已添加。

**Comment by SuLingGG** [comment]
> 功能已添加。

Dalao 太棒辣~
