### ISSUE TITLE
pro会员上传的文件有效期24小时

### ISSUE THREAD

**Issue by rubbislam** [Mikubill/cowtransfer-uploader#41]
用最新的cowtransfer-uploader上传文件：
`cowtransfer-uploader -c "remember-mev2=xxxxxxxx;" -a "yyyyyyyyyyy" -p 8 file`

之后显示上传成功，没有提示错误。使用链接也能下载成功。然而，文件的有效期只有24小时，跟pro会员的特权不一致。另外我在自己的云盘里面也没有找到上传成功的文件。

换了几次cookie和token都是一样的结果。

另外，请问能让文件上传到某个指定的云文件夹里？

**Comment by Aixzk** [comment]
据我所知 cowtransfer-uploader 并没有上传文件到奶牛快传网盘里的功能，只有传输文件。

如果 cookie 和 token 都是有效且正确的，有效期也不应该只有 24 小时，也许你应该检查是否都填写正确。

给个简单的检查方法：直接上传单个超过 2GB 的文件，如果 cookie 和 token 不正确的话会报错：

```
getSendConfig(single mode) returns error: File size exceed, no payment found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x73462d]
...
```
