### ISSUE TITLE
上传后的文件无法下载

### ISSUE THREAD

**Issue by Bearcatail** [Mikubill/cowtransfer-uploader#52]
下载会显示 `{"error":"Document not found"}`

**Comment by Mikubill** [comment]
已确认。可能需要修改上传流程

**Comment by Mikubill** [comment]
好像只是改了个busket名，修了== https://github.com/Mikubill/cowtransfer-uploader/commit/fbb77194691f497f12c72140cd61a17ace5c9a1b

**Comment by Bearcatail** [comment]
不是 bucket 吗（

**Comment by Mikubill** [comment]
手抽了Orz
