### ISSUE TITLE
下载文件时能否校验hash值？

### ISSUE THREAD

**Issue by njzjz** [Mikubill/cowtransfer-uploader#6]
下载大文件时，经常出现下载的文件和源文件大小一样，但hash值不一致的情况。反复重新下载，能下到正确的文件，说明上传的文件没问题，可能是下载过程中的网络问题？
如果可行，希望能够在文件损坏时自动重下。
ps：奶牛快传在美国的速度十分玄学，最快能达到40MB/s，最慢只有400KB/s。

**Comment by Mikubill** [comment]
貌似在开启多线程下载时会出现此问题，可以在下载时暂时将线程数降低（设置为4以下）以避免错误。

**Comment by Mikubill** [comment]
已尝试修复了潜在的下载问题，可以重新测试一下

**Comment by Mikubill** [comment]
closed.
（貌似已修复；如有问题可以重新打开）
