### ISSUE TITLE
使用Cookie选项无法正常登录

### ISSUE THREAD

**Issue by chenyang12315** [Mikubill/cowtransfer-uploader#9]
因有分享大文件的需要，购买了专业版账户。在尝试使用Cookie方式登陆时，提示

> etSendConfig(single mode) returns error: **File size exceed, no payment found**

如果上传小文件，同样的命令可以上传，但完成后Web面板中看不到传输记录（应该是没有登陆成功）。

所尝试使用命令如下：
a. ` ./cowtransfer-uploader -cookie="remember-me=b0VUY省略zcz**;**" -s -p 8 --hash --password=acase /www/zshare/Aria2/Download/VCS`

b. `./cowtransfer-uploader -cookie="remember-me=b0VUY省略zcz" -s -p 8 --hash --password=acase /www/zshare/Aria2/Download/VCS`

c. `./cowtransfer-uploader -c "remember-me=b0VUY省略zcz" -s -p 8 --hash --password=acase /www/zshare/Aria2/Download/VCS`

_所用Cookie为清空Cookie记录后重新登陆得到的。_

1. 请帮忙查看上述--cookie命令使用是否正确
2. [Readme.md](https://github.com/Mikubill/cowtransfer-uploader/blob/master/README.md)中所给--cookie实例，引号内末尾有一个”;“，查看浏览器cookie值无此内容，是否需要保留？
3. 请验证Cookie remember-me登陆方式是否仍然有效。

谢谢！

**Comment by Mikubill** [comment]
貌似cookie验证出现了问题，稍后我检查一下（怎么老改API

**Comment by Mikubill** [comment]
已修复，可以在最新版本中测试。

**Comment by Mikubill** [comment]
closed.(fixed)
